<!DOCTYPE html>
<html lang="en">

<head>
	<title>Analysis</title>
	<meta charset="utf-8" />	
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">	
	<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">
	<link rel="icon" href="/images/favicon.ico" type="image/x-icon">
    
    <!-- CSS -->	
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
	<link rel="stylesheet" href="/jquery-ui.css">	    
	<link rel="stylesheet" href="/css/analysis-style.css" type="text/css">  
    
    <!-- JS -->    
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
	<script src="/jquery-ui.js"></script>	
	<script src="//d3js.org/d3.v3.min.js"></script>
	
<?php if($this->debug == 1) {?>
   		
<script>
function popupWin() {
	text =  "<html>\n<head>\n<title>Pop Window</title>\n<body>\n";
	text += "<center>\n<br>";
	text += "<table><tr><td valign=top><?php echo($this->log1);?></td><td valign=top><?php echo($this->log2);?></td><td valign=top><?php echo($this->log3);?></td><td valign=top><?php echo($this->log4);?></td></tr></table>";
	text += "</center>\n</body>\n</html>\n";
	setTimeout('windowProp(text)', 2000); 		// delay 3 seconds before opening
}

function windowProp(text) {
	newWindow = window.open('','newWin','width=900,height=500');
	newWindow.document.write(text);
	//setTimeout('closeWin(newWindow)', 5000);	// delay 5 seconds before closing
}

</script>	
<?php }?>
	
</head>	

<?php if($this->debug == 1) {?>
<body class="body" onLoad="popupWin()">
<?php } else {?>
<body class="body">	
<?php }?>

<body class="body">		
	<div class="mainContent">	
			<div id="chart"></div>
			
			<div class="nav-thumb"> 
			<ol>
			        <li id="step_1"><a class="1" data-slide="1"></a></li>
			        <li id="step_2"><a class="2" data-slide="2"></a></li>
			        <li id="step_3"><a  class="3" data-slide="3"></a></li>
			        <li id="step_4"><a  class="4" data-slide="4"></a></li>					        
			 </ol>
			 </div>
			<div id="clickerWrapper">						
				<div id="clicker">Next</div>
			</div>
			<div id="buttonWrapper">
				<div id="buttonWrapperInner">
					<!-- 
					<div id="reset" class="sideButton">RESET</div>
					<div id="link" class="sideButton">&nbsp;</div>	
					 
					 Filter By
					<div class="sideButton">					
				    <form action="/analysis" method="post">
				    <input type="hidden" id="q0_hidden" name="q0" value="<?php echo($this->surveyId);?>">
				    <input type="hidden" id="q1_hidden" name="q1" value="<?php echo($this->q1Answer);?>">
				    <input type="hidden" id="q2_hidden" name="q2" value="<?php echo($this->q2Answer);?>">
				    <input type="hidden" id="q31_hidden" name="q3_1" value="<?php echo($this->q31Answer);?>">
				    <input type="hidden" id="q32_hidden" name="q3_2" value="<?php echo($this->q32Answer);?>">
				    <input type="hidden" id="q33_hidden" name="q3_3" value="<?php echo($this->q33Answer);?>">
				    <input type="hidden" id="q34_hidden" name="q3_4" value="<?php echo($this->q34Answer);?>">
				    <input type="hidden" id="q35_hidden" name="q3_5" value="<?php echo($this->q35Answer);?>">
				    <input type="hidden" id="q41_hidden" name="q4_1" value="<?php echo($this->q41Answer);?>">
				    <input type="hidden" id="q42_hidden" name="q4_2" value="<?php echo($this->q42Answer);?>">
				    <input type="hidden" id="q43_hidden" name="q4_3" value="<?php echo($this->q43Answer);?>">
				    <input type="hidden" id="q44_hidden" name="q4_4" value="<?php echo($this->q44Answer);?>">
				    <input type="hidden" id="q45_hidden" name="q4_5" value="<?php echo($this->q45Answer);?>">				    
				    <input type="hidden" id="q43_hidden" name="region" value="<?php echo($this->region);?>">
				    <input type="hidden" id="q44_hidden" name="business_model" value="<?php echo($this->business_model);?>">
				    <input type="hidden" id="q45_hidden" name="company_size" value="<?php echo($this->company_size);?>">				    
				    <select name="filter" style="width: 200px"  onchange="this.form.submit()">
				      <option value="" <?php echo(empty($this->currentFilter) ? 'selected' : '')?>>No Filter</option>
					  <option value="qs4_<?php echo($this->businessModelValue);?>" <?php echo(strpos($this->currentFilter, 's4_') ? 'selected' : '')?>><?php echo($this->businessModelLabel);?></option>
				      <option value="qregion_<?php echo($this->regionValue);?>" <?php echo(strpos($this->currentFilter, 'region_') ? 'selected' : '')?>><?php echo($this->regionLabel);?></option>
					  <option value="qs2_<?php echo($this->companySizeValue);?>" <?php echo(strpos($this->currentFilter, 's2_') ? 'selected' : '')?>><?php echo($this->companySizeLabel);?></option>

					</select>
				    </form>
				    			 
					</div>
					-->
					<div id="link" class="sideButton">&nbsp;</div>
				</div>
			</div>
	</div>
<script>

$("document").ready(function() {
	
	$("ol > li:first").addClass('active');

	$("#step_1").click(function(){
		d3.select("svg").remove();
		initSvg();
		stopClicker(1000);
		
		renderQ1Result(1);

		setTimeout(function(){
			startClicker(1000);
		}, 4000);
		
		counter = 1;
		$("ol > li").removeClass('active');
		$("ol > li:first").addClass('active');
	});

	$("#step_2").click(function(){ 
		d3.select("svg").remove();
		initSvg();
		stopClicker(1000);
		
		renderQ1Result(0);
		renderQ2Result(1);

		counter = 2;
		$("ol > li").removeClass('active');
		$("ol > li:eq(1)").addClass('active');
	});

	$("#step_3").click(function(){ 
		d3.select("svg").remove();
		initSvg();
		stopClicker(1000);
		
		renderQ1Result(0);
		renderQ2Result(0);
		renderQ3Result(1);		
		counter = 3;
		$("ol > li").removeClass('active');
		$("ol > li:eq(2)").addClass('active');
	});

	$("#step_4").click(function(){ 
		d3.select("svg").remove();
		initSvg();
		stopClicker(1000);
		
		renderQ1Result(0);
		renderQ2Result(0);
		renderQ3Result(0);
		renderQ4Result(1);		

		counter = 4;
		$("ol > li").removeClass('active');
		$("ol > li:eq(3)").addClass('active');
	});
	

	$('#info_popup').dialog( { 
		autoOpen: false,
		width:480,
		modal: true		
	});

	$('#incomplete_error').dialog( { 
		autoOpen: false,
		width:420,
		modal: true,
		buttons: [
		            {
		              text: "OK",
		              click: function() {
		                $( this ).dialog( "close" );
		              }
		            }
		          ]	
	});

	$('#disclosure_error').dialog( { 
		autoOpen: false,
		width:420,
		modal: true,
		buttons: [
		            {
		              text: "OK",
		              click: function() {
		                $( this ).dialog( "close" );
		              }
		            }
		          ]	
	});
	
}); 	

var margin = {top: 0, right: 0, bottom: 0, left: 0},
width = 800 - margin.left - margin.right,
height = 550 - margin.top - margin.bottom,

radius = Math.min(width, height) * .47,

//benchmarkArc
innerRadius = Math.min(width, height) * .32, 
outerRadius = innerRadius * 1.14,

//surveyArc
innerRadius2 = Math.min(width, height) * .37,
outerRadius2 = innerRadius2 * 1.11;
t = 2 * Math.PI; 

var benchmarkArc = d3.svg.arc()
	.innerRadius(innerRadius)
	.outerRadius(outerRadius);

var surveyArc = d3.svg.arc()
	.innerRadius(innerRadius2)
	.outerRadius(outerRadius2);

var chartDiv = d3.select("#chart");
var svg;
var textCenter;
var middleTextTop;
var middleTextMiddle;
var middleTextBottom;

function initSvg()	
{

svg = chartDiv.append("svg")
	.attr("width", width)
	.attr("height", height)
	.append("g")
	.attr("transform", "translate(" + width / 2 + "," + height / 2 + ")");
		
textCenter = svg.append("g")
  .attr("class", "explanationWrapper");

// Initial Text  
middleTextTop = textCenter.append("text")
	.attr("class", "explanation")
	.style("fill","#00b3ee")
	.attr("text-anchor", "middle")
	.attr("x", 0 + "px")
	.attr("y", -24*10/2 + "px")
	.attr("dy", "1em")
	.attr("opacity", 1)
	.text("")
	.call(wrap, 300);

middleTextMiddle = textCenter.append("text")
	.attr("class", "explanation")
	.style("fill","#00b3ee")
	.attr("text-anchor", "middle")
	.attr("x", 0 + "px")
	.attr("y", 24*3/2 + "px")
	.attr("dy", "1em")
	.attr('opacity', 1)
	.text("")
	.call(wrap, 300);

middleTextBottom = textCenter.append("text")
	.attr("class", "explanation")
	.style("fill","#00b3ee")
	.attr("text-anchor", "middle")
	.attr("x", 0 + "px")
	.attr("y", 24*3/2 + "px")
	.attr("dy", "1em")
	.attr('opacity', 1)
	.text("")	
	.call(wrap, 300);  
}

initSvg();


var buttonTexts = ["Next","Next","Next","Click here for your full report"];

renderQ1Result(1);
var counter = 3;

d3.select("#reset")
.on("click", function(e) {location.reload();});

stopClicker(1000);

setTimeout(function(){
	startClicker(1000);
}, 4000);

counter = 1;

d3.select("#clicker").on("click", function(e){
	
	if (counter == 1) {
		$("ol > li").removeClass('active');
		$("ol > li:eq(1)").addClass('active');
	
		stopClicker(1000);
		renderQ2Result(1);
	    
	} else if (counter == 2) {
		$("ol > li").removeClass('active');
		$("ol > li:eq(2)").addClass('active');
		
		stopClicker(1000);
		renderQ3Result(1);

	
	} else if (counter == 3) {
		$("ol > li").removeClass('active');
		$("ol > li:eq(3)").addClass('active');
				
		stopClicker(1000);
		renderQ4Result(1);


	} else if (counter == 4) {
		$("#info_popup").dialog("open");
		//counter = counter - 1;
	}
	
	counter = counter + 1;
	
	d3.select("#clicker").text(buttonTexts[counter-2]);
});

//Wraps SVG text*/
function wrap(text, width) {
    var text = d3.select(this[0][0]),
        words = text.text().split(/\s+/).reverse(),
        word,
        line = [],
        lineNumber = 0,
        lineHeight = 1.4, 
        y = text.attr("y"),
		x = text.attr("x"),
        dy = parseFloat(text.attr("dy")),
        tspan = text.text(null).append("tspan").attr("x", x).attr("y", y).attr("dy", dy + "em");
		
    while (word = words.pop()) {
      line.push(word);
      tspan.text(line.join(" "));
      if (tspan.node().getComputedTextLength() > width) {
        line.pop();
        tspan.text(line.join(" "));
        line = [word];
        tspan = text.append("tspan").attr("x", x).attr("y", y).attr("dy", ++lineNumber * lineHeight + dy + "em").text(word);
      };
    };  
};

/*Transition the top circle text*/
function changeTopText (newText, loc, delayDisappear, delayAppear, finalText, xloc, w) {

	/*If finalText is not provided, it is not the last text of the Draw step*/
	if(typeof(finalText)==='undefined') finalText = false;
	
	if(typeof(xloc)==='undefined') xloc = 0;
	if(typeof(w)==='undefined') w = 280;
	
	middleTextTop	
		/*Current text disappear*/
		.transition().delay(700 * delayDisappear).duration(700)
		.attr('opacity', 0)	
		/*New text appear*/
		.call(endall,  function() {
			middleTextTop.text(newText)
			.attr("y", -24*loc + "px")
			.attr("x", xloc + "px")
			.call(wrap, w);	
		})
		.transition().delay(700 * delayAppear).duration(700)
		.attr('opacity', 1)
		.call(endall,  function() {
			if (finalText == true) {
				if (counter == 4) {
					d3.select("#clicker")
					.text(buttonTexts[counter-1])
					.style("pointer-events", "auto")
					.transition().duration(400)
					.style("border-color", "#363636")
					.style("color", "#00b3ee")
					.style("text-decoration", "underline");
				} else {
					d3.select("#clicker")
					.text(buttonTexts[counter-1])
					.style("pointer-events", "auto")
					.transition().duration(400)
					.style("border-color", "#363636")
					.style("color", "#363636")
					.style("text-decoration", "none");
				}

			};
		});
}/*changeTopText */


function changeMiddleText (newText, loc, delayDisappear, delayAppear, classname) {
	middleTextMiddle
		.transition().delay(700 * delayDisappear).duration(700)
		.attr('opacity', 0)
		.call(endall,  function() {
			middleTextMiddle.text(newText)
			.attr("class", classname)
			.attr("y", 24*loc + "px")
			.call(wrap, 300);	
		})
		.transition().delay(700 * delayAppear).duration(700)
		.attr('opacity', 1);
}

/*Transition the bottom circle text*/
function changeBottomText (newText, loc, delayDisappear, delayAppear, classname) {
	middleTextBottom
		/*Current text disappear*/
		
		.transition().delay(700 * delayDisappear).duration(700)
		.attr('opacity', 0)
		/*New text appear*/
		.call(endall,  function() {
			middleTextBottom.text(newText)
			.attr("class", classname)
			.attr("y", 24*loc + "px")
			.call(wrap, 300);	
		})
		.transition().delay(700 * delayAppear).duration(700)
		//.attr("class", classname)
		.attr('opacity', 1);
}/*changeTopText*/

function endall(transition, callback) { 
    var n = 0; 
    transition 
        .each(function() { ++n; }) 
        .each("end", function() { if (!--n) callback.apply(this, arguments); }); 
}/*endall*/ 

function stopClicker(stopDuration) {
	d3.select("#clicker")
	.style("pointer-events", "none")
	.transition().duration(700)	
	.style("border-color", "#D3D3D3")
	.style("color", "#D3D3D3");		
};

function startClicker(stopDuration) {
		d3.select("#clicker")
		.style("pointer-events", "auto")
		.transition().duration(400)		
		.style("border-color", "#363636")
		.style("color", "#363636");

};


function renderQ1Result(delayFlag)
{
	/* white background for surveyArc */
	svg.append("path")
	.attr("id", "q1")
	.datum({startAngle: 0, endAngle: .25*t})
	.style("stroke", "#FFF")
	.style("fill", "#FFF")
	.attr("d", surveyArc);

	/* white background for benchmarkArc */
	svg.append("path")
	.attr("id", "q1-1")
	.datum({startAngle: 0, endAngle: .25*t})
	.style("stroke", "#FFF")
	.style("fill", "#FFF")
	.attr("d", benchmarkArc);		

	/* benchmarkArc, inner Arc */
	/* surveyArc, outter Arc */	
	if (delayFlag == 1) {
		svg.append("path")
		.attr("id", "q1benchmark")
		.datum({startAngle: 0, endAngle: <?php echo($this->q1BenchmarkAngle);?>*t})
		.style("stroke", "#e6e6e6")	
		.style("fill", "#e6e6e6")
		.transition().duration(200)
		.attr("d", benchmarkArc)
		.attrTween("d", function(d) {
			   var i = d3.interpolate(0, <?php echo($this->q1BenchmarkAngle);?>*t);
			   return function(t) {
				   d.endAngle = i(t);
				 return benchmarkArc(d);
			   }
		});
		
		svg.append("path")
		.attr("id", "q1survey")
		.datum({startAngle: 0, endAngle: <?php echo($this->q1SurveyAngle);?>*t})
		//.style("stroke", "#fdec99")
		//.style("fill", "#fdec99")
		.style("stroke", "#fad000")
		.style("fill", "#fad000")
		.transition().duration(2000)	
		.attr("d", surveyArc)
		.attrTween("d", function(d) {
			   var i = d3.interpolate(0, <?php echo($this->q1SurveyAngle);?>*t);
			   return function(t) {
				   d.endAngle = i(t);
				 return surveyArc(d);
			   }
		});	
	} else {
		svg.append("path")
		.attr("id", "q1benchmark")
		.datum({startAngle: 0, endAngle: <?php echo($this->q1BenchmarkAngle);?>*t})
		.style("stroke", "#e6e6e6")	
		.style("fill", "#e6e6e6")
		.attr("d", benchmarkArc)
		.transition().duration(0)
		.attrTween("d", function(d) {
			   var i = d3.interpolate(0, <?php echo($this->q1BenchmarkAngle);?>*t);
			   return function(t) {
				   d.endAngle = i(t);
				 return benchmarkArc(d);
			   }
		});
		
		svg.append("path")
		.attr("id", "q1survey")
		.datum({startAngle: 0, endAngle: <?php echo($this->q1SurveyAngle);?>*t})
		.style("stroke", "#fad000")
		.style("fill", "#fad000")
		.attr("d", surveyArc)
		.transition().duration(0)
		.attrTween("d", function(d) {
			   var i = d3.interpolate(0, <?php echo($this->q1SurveyAngle);?>*t);
			   return function(t) {
				   d.endAngle = i(t);
				 return surveyArc(d);
			   }
		});	
	}
	


	setTimeout(function(){
		svg.append("text")
	    .style("font-size","14px")
	    .style("fill","#00b3ee")
		.attr("x", 5)  
	    .attr("dy",-10)			
	    .append("textPath")
	    .attr("xlink:href","#q1")
	    .style("text-anchor","left") // using "end", the entire text disappears
	    .text(" Q1. Number Of Systems Used To Capture Data");
	}, (delayFlag == 1) ? 1500 : 0);


	setTimeout(function(){
		svg.append("text")
	    .style("font-size","14px")
	    .style("fill","#fff")
		.attr("x", 5)   //Move the text from the start angle of the arc
		.attr("dy", 18) //Move the text down
	    .append("textPath")
	    .attr("xlink:href","#q1survey")
	    .style("text-anchor","left") // using "end", the entire text disappears
	    .text(" You are <?php echo($this->q1MyPercent);?>% of Average");
	}, (delayFlag == 1) ? 1500 : 0);


	setTimeout(function(){
		svg.append("text")
	    .style("font-size","14px")
	    .style("fill","#fff")
		.attr("x", 5)   //Move the text from the start angle of the arc
		.attr("dy", 18) //Move the text down
	    .append("textPath")
	    .attr("xlink:href","#q1benchmark")
	    .style("text-anchor","left") // using "end", the entire text disappears
	    .text(" Industry Average");
	}, (delayFlag == 1) ? 1500 : 0);


	changeTopText(newText = "<?php echo($this->q1Analysis1);?>",
			loc = 8/2, delayDisappear = 0, delayAppear = (delayFlag == 1) ? 3 : 0);

	changeMiddleText(newText = "<?php echo($this->q1Analysis2);?>",
			loc = -4/2, delayDisappear = 0, delayAppear = (delayFlag == 1) ? 4 : 0, classname="explanationbold");

	changeBottomText(newText = "<?php echo($this->q1Analysis3);?>",
			loc = 2/2, delayDisappear = 0, delayAppear = (delayFlag == 1) ? 4 : 0, classname="explanation");
		
}

function renderQ2Result(delayFlag)
{
	/* white background for surveyArc */
	svg.append("path")
	.attr("id", "q2")
	.datum({startAngle: .25*t, endAngle: .5*t})
	.style("stroke", "#FFF")
	.style("fill", "#FFF")
	.attr("d", surveyArc);

	/* white background for benchmarkArc */
	svg.append("path")
	.attr("id", "q2-1")
	.datum({startAngle: .25*t, endAngle: .5*t})
	.style("stroke", "#FFF")
	.style("fill", "#FFF")
	.attr("d", benchmarkArc);

	/* benchmarkArc, inner Arc */
	/* surveyArc, outter Arc */	
	if (delayFlag == 1) {
		svg.append("path")
		.attr("id", "q2benchmark")
		.datum({startAngle: .25*t, endAngle: <?php echo($this->q2BenchmarkAngle);?>*t})
		.style("stroke", "#cccccc")	
		.style("fill", "#cccccc")
		.transition().duration(200)	
		.attr("d", benchmarkArc)
		.attrTween("d", function(d) {
			   var i = d3.interpolate(.25*t, <?php echo($this->q2BenchmarkAngle);?>*t);
			   return function(t) {
				   d.endAngle = i(t);
				 return benchmarkArc(d);
			   }
		});
		
		svg.append("path")
		.attr("id", "q2survey")		
		.datum({startAngle: .25*t, endAngle: <?php echo($this->q2SurveyAngle);?>*t})
		//.style("stroke", "#fce366")
		//.style("fill", "#fce366")
		.style("stroke", "#e8b720")
		.style("fill", "#e8b720")		
		.transition().duration(2000)	
		.attr("d", surveyArc)
		.attrTween("d", function(d) {
			   var i = d3.interpolate(.25*t, <?php echo($this->q2SurveyAngle);?>*t);
			   return function(t) {
				   d.endAngle = i(t);
				 return surveyArc(d);
			   }
		});	
	} else {
		svg.append("path")
		.attr("id", "q2benchmark")
		.datum({startAngle: .25*t, endAngle: <?php echo($this->q2BenchmarkAngle);?>*t})
		.style("stroke", "#cccccc")	
		.style("fill", "#cccccc")
		.transition().duration(0)	
		.attr("d", benchmarkArc)
		.attrTween("d", function(d) {
			   var i = d3.interpolate(.25*t, <?php echo($this->q2BenchmarkAngle);?>*t);
			   return function(t) {
				   d.endAngle = i(t);
				 return benchmarkArc(d);
			   }
		});
		
		svg.append("path")
		.attr("id", "q2survey")		
		.datum({startAngle: .25*t, endAngle: <?php echo($this->q2SurveyAngle);?>*t})
		.style("stroke", "#e8b720")
		.style("fill", "#e8b720")
		.transition().duration(0)	
		.attr("d", surveyArc)
		.attrTween("d", function(d) {
			   var i = d3.interpolate(.25*t, <?php echo($this->q2SurveyAngle);?>*t);
			   return function(t) {
				   d.endAngle = i(t);
				 return surveyArc(d);
			   }
		});			
	}
	
    setTimeout(function(){
		svg.append("text")
        .style("font-size","14px")
        .style("fill","#00b3ee")
		.attr("x", 5)  
        .attr("dy",-10)			
        .append("textPath")
        .attr("xlink:href","#q2")
        .style("text-anchor","left") // using "end", the entire text disappears
        .text(" Q2. Plan to move to a single customer database");
    }, (delayFlag == 1) ? 1500 : 0);

    
    setTimeout(function(){
		svg.append("text")
        .style("font-size","14px")
        .style("fill","#fff")
		.attr("x", 5)   //Move the text from the start angle of the arc
		.attr("dy", 18) //Move the text down
        .append("textPath")
        .attr("xlink:href","#q2survey")
        .style("text-anchor","left") // using "end", the entire text disappears
        .text(" You are <?php echo($this->q2MyPercent);?>% of Average");
    }, (delayFlag == 1) ? 1500 : 0);

    	    
    setTimeout(function(){
		svg.append("text")
        .style("font-size","14px")
        .style("fill","#fff")
		.attr("x", 5)   //Move the text from the start angle of the arc
		.attr("dy", 18) //Move the text down
        .append("textPath")
        .attr("xlink:href","#q2benchmark")
        .style("text-anchor","left") // using "end", the entire text disappears
        .text(" Industry Average");
    }, (delayFlag == 1) ? 1500 : 0);		

	changeTopText(newText = "<?php echo($this->q2Analysis1);?>",
			loc = 8/2, delayDisappear = 0, delayAppear = (delayFlag == 1) ? 3 : 0, finalText = true);
	
	changeMiddleText(newText = "<?php echo($this->q2Analysis2);?>",
			loc = -4/2, delayDisappear = 0, delayAppear = (delayFlag == 1) ? 4 : 0, classname="explanationbold");
				
	changeBottomText(newText = "<?php echo($this->q2Analysis3);?>",
			loc =2/2, delayDisappear = 0, delayAppear = (delayFlag == 1) ? 4 : 0, classname="explanation");
		

}

function renderQ3Result(delayFlag)
{
	svg.append("path")
	.attr("id", "q3")
	.datum({startAngle: .5*t, endAngle: .75*t})
	.style("stroke", "#FFF")
	.style("fill", "#FFF")
	.attr("d", surveyArc);
	
	svg.append("path")
	.attr("id", "q3-1")
	.datum({startAngle: .5*t, endAngle: .75*t})
	.style("stroke", "#FFF")
	.style("fill", "#FFF")
	.attr("d", benchmarkArc);

	if (delayFlag == 1) {
		svg.append("path")
		.attr("id", "q3benchmark")			
		.datum({startAngle: .5*t, endAngle: <?php echo($this->q3BenchmarkAngle);?>*t})
		.style("stroke", "#b3b3b3")	
		.style("fill", "#b3b3b3")
		.transition().duration(200)	
		.attr("d", benchmarkArc)
		.attrTween("d", function(d) {
			   var i = d3.interpolate(.5*t, <?php echo($this->q3BenchmarkAngle);?>*t);
			   return function(t) {
				   d.endAngle = i(t);
				 return benchmarkArc(d);
			   }
		});	
		
		svg.append("path")
		.attr("id", "q3survey")			
		.datum({startAngle: .5*t, endAngle: <?php echo($this->q3SurveyAngle);?>*t})
		//.style("stroke", "#fdce00")
		//.style("fill", "#fdce00")		
		.style("stroke", "#dea400")
		.style("fill", "#dea400")
		.transition().duration(2000)	
		.attr("d", surveyArc)
		.attrTween("d", function(d) {
			   var i = d3.interpolate(.5*t, <?php echo($this->q3SurveyAngle);?>*t);
			   return function(t) {
				   d.endAngle = i(t);
				 return surveyArc(d);
			   }
		});
	} else {
		svg.append("path")
		.attr("id", "q3benchmark")			
		.datum({startAngle: .5*t, endAngle: <?php echo($this->q3BenchmarkAngle);?>*t})
		.style("stroke", "#b3b3b3")	
		.style("fill", "#b3b3b3")
		.transition().duration(0)	
		.attr("d", benchmarkArc)
		.attrTween("d", function(d) {
			   var i = d3.interpolate(.5*t, <?php echo($this->q3BenchmarkAngle);?>*t);
			   return function(t) {
				   d.endAngle = i(t);
				 return benchmarkArc(d);
			   }
		});	
		
		svg.append("path")
		.attr("id", "q3survey")			
		.datum({startAngle: .5*t, endAngle: <?php echo($this->q3SurveyAngle);?>*t})
		.style("stroke", "#dea400")
		.style("fill", "#dea400")
		.transition().duration(0)	
		.attr("d", surveyArc)
		.attrTween("d", function(d) {
			   var i = d3.interpolate(.5*t, <?php echo($this->q3SurveyAngle);?>*t);
			   return function(t) {
				   d.endAngle = i(t);
				 return surveyArc(d);
			   }
		});
	}
	
		
	
	
	setTimeout(function(){
		svg.append("text")
	    .style("font-size","14px")
	    .style("fill","#00b3ee")
		.attr("x", 5)  
	    .attr("dy",-10)			
	    .append("textPath")
	    .attr("xlink:href","#q3")
	    .style("text-anchor","left") // using "end", the entire text disappears
	    .text(" Q3. Plans to use advanced analytics");
	}, (delayFlag == 1) ? 1500 : 0);
	
	setTimeout(function(){
		svg.append("text")
	    .style("font-size","14px")
	    .style("fill","#fff")
		.attr("x", 5)   //Move the text from the start angle of the arc
		.attr("dy", 17) //Move the text down
	    .append("textPath")
	    .attr("xlink:href","#q3survey")
	    .style("text-anchor","left") // using "end", the entire text disappears
	    .text(" You are <?php echo($this->q3MyPercent);?>% of Average");
	}, (delayFlag == 1) ? 1500 : 0);
	
		    
	setTimeout(function(){
		svg.append("text")
	    .style("font-size","14px")
	    .style("fill","#fff")
		.attr("x", 5)   //Move the text from the start angle of the arc
		.attr("dy", 17) //Move the text down
	    .append("textPath")
	    .attr("xlink:href","#q3benchmark")
	    .style("text-anchor","left") // using "end", the entire text disappears
	    .text(" Industry Average");
	}, (delayFlag == 1) ? 1500 : 0);
	
	changeTopText(newText = "<?php echo($this->q3Analysis1_1);?>",
			loc = 8/2, delayDisappear = 0, delayAppear = (delayFlag == 1) ? 3 : 0, finalText = true);
	
	changeMiddleText(newText = "<?php echo($this->q3Analysis1_2);?>",
			loc = -4/2, delayDisappear = 0, delayAppear = (delayFlag == 1) ? 4 : 0, classname="explanationbold");
				
	changeBottomText(newText = "<?php echo($this->q3Analysis1_3);?>",
			loc = 2/2, delayDisappear = 0, delayAppear = (delayFlag == 1) ? 4 : 0, classname="explanation");
}

function renderQ4Result(delayFlag)
{
	svg.append("path")
	.attr("id", "q4")
	.datum({startAngle: .75*t, endAngle: t})
	.style("stroke", "#FFF")
	.style("fill", "#FFF")
	.attr("d", surveyArc);

	svg.append("path")
	.attr("id", "q4-1")
	.datum({startAngle: .75*t, endAngle: t})
	.style("stroke", "#FFF")
	.style("fill", "#FFF")
	.attr("d", benchmarkArc);

	if (delayFlag == 1) {
		svg.append("path")
		.attr("id", "q4benchmark")
		.datum({startAngle: .75*t, endAngle: <?php echo($this->q4BenchmarkAngle);?>*t})
		.style("stroke", "#999999")	
		.style("fill", "#999999")
		.transition().duration(200)	
		.attr("d", surveyArc)
		.attrTween("d", function(d) {
			   var i = d3.interpolate(.75*t, <?php echo($this->q4BenchmarkAngle);?>*t);
			   return function(t) {
				   d.endAngle = i(t);
				 return benchmarkArc(d);
			   }
		});	
		
		svg.append("path")
		.attr("id", "q4survey")		
		.datum({startAngle: .75*t, endAngle: <?php echo($this->q4SurveyAngle);?>*t})
		//.style("stroke", "#dea400")
		//.style("fill", "#dea400")		
		.style("stroke", "#ce9509")
		.style("fill", "#ce9509")
		.transition().duration(2000)	
		.attr("d", surveyArc)
		.attrTween("d", function(d) {
			   var i = d3.interpolate(.75*t, <?php echo($this->q4SurveyAngle);?>*t);
			   return function(t) {
				   d.endAngle = i(t);
				 return surveyArc(d);
			   }
		});
	} else {
		svg.append("path")
		.attr("id", "q4benchmark")
		.datum({startAngle: .75*t, endAngle: <?php echo($this->q4BenchmarkAngle);?>*t})
		.style("stroke", "#999999")	
		.style("fill", "#999999")
		.transition().duration(0)	
		.attr("d", surveyArc)
		.attrTween("d", function(d) {
			   var i = d3.interpolate(.75*t, <?php echo($this->q4BenchmarkAngle);?>*t);
			   return function(t) {
				   d.endAngle = i(t);
				 return benchmarkArc(d);
			   }
		});	
		
		svg.append("path")
		.attr("id", "q4survey")		
		.datum({startAngle: .75*t, endAngle: <?php echo($this->q4SurveyAngle);?>*t})
		.style("stroke", "#ce9509")
		.style("fill", "#ce9509")
		.transition().duration(0)	
		.attr("d", surveyArc)
		.attrTween("d", function(d) {
			   var i = d3.interpolate(.75*t, <?php echo($this->q4SurveyAngle);?>*t);
			   return function(t) {
				   d.endAngle = i(t);
				 return surveyArc(d);
			   }
		});
	}			



    setTimeout(function(){
		svg.append("text")
        .style("font-size","14px")
        .style("fill","#00b3ee")
		.attr("x", 5)  
        .attr("dy",-10)			
        .append("textPath")
        .attr("xlink:href","#q4")
        .style("text-anchor","left") // using "end", the entire text disappears
        .text(" Q4. Ability to respond to customer in real-time");
    }, (delayFlag == 1) ? 1500 : 0);

    setTimeout(function(){
		svg.append("text")
        .style("font-size","14px")
        .style("fill","#fff")
		.attr("x", 5)   //Move the text from the start angle of the arc
		.attr("dy", 17) //Move the text down
        .append("textPath")
        .attr("xlink:href","#q4survey")
        .style("text-anchor","left") // using "end", the entire text disappears
        .text(" You are <?php echo($this->q4MyPercent);?>% of Average");
    }, (delayFlag == 1) ? 1500 : 0);
    	    
    setTimeout(function(){
		svg.append("text")
        .style("font-size","14px")
        .style("fill","#fff")
		.attr("x", 5)   //Move the text from the start angle of the arc
		.attr("dy", 17) //Move the text down
        .append("textPath")
        .attr("xlink:href","#q4benchmark")
        .style("text-anchor","left") // using "end", the entire text disappears
        .text(" Industry Average");
    }, (delayFlag == 1) ? 1500 : 0);

    changeTopText(newText = "<?php echo($this->q4Analysis1_1);?>",
			loc =8/2, delayDisappear = 0, delayAppear = (delayFlag == 1) ? 3 : 0, finalText = true);
	
	changeMiddleText(newText = "<?php echo($this->q4Analysis1_2);?>",
			loc = -4/2, delayDisappear = 0, delayAppear = (delayFlag == 1) ? 4 : 0, classname="explanationbold");
				
	changeBottomText(newText = "<?php echo($this->q4Analysis1_3);?>",
			loc = 2/2, delayDisappear = 0, delayAppear = (delayFlag == 1) ? 4 : 0, classname="explanation");	
}


function validateData()
{
	if ($('input[name="first_name"]').val() == '' ||
			$('input[name="last_name"]').val() == '' ||
			$('input[name="company_name"]').val() == '' ||
			$('input[name="job_title"]').val() == '' ||
			$('input[name="email"]').val() == '') {
		$("#incomplete_error").dialog("open");
		return false;
	}
/*	
	if ($('input[name="disclosure"]').val() != 'Yes') {
		$("#disclosure_error").dialog("open");
		return false;
	}
*/
	return true;	
}

</script>

<!-- Popup form -->	
  <div id="info_popup" class="infowindow">
    <form action="/summary" method="post" onsubmit="return validateData();">
    <input type="hidden" id="q0_hidden" name="q0" value="<?php echo($this->surveyId);?>">
    <input type="hidden" id="q1_hidden" name="q1" value="<?php echo($this->q1Answer);?>">
    <input type="hidden" id="q2_hidden" name="q2" value="<?php echo($this->q2Answer);?>">
    <input type="hidden" id="q31_hidden" name="q3_1" value="<?php echo($this->q31Answer);?>">
    <input type="hidden" id="q32_hidden" name="q3_2" value="<?php echo($this->q32Answer);?>">
    <input type="hidden" id="q33_hidden" name="q3_3" value="<?php echo($this->q33Answer);?>">
    <input type="hidden" id="q34_hidden" name="q3_4" value="<?php echo($this->q34Answer);?>">
    <input type="hidden" id="q35_hidden" name="q3_5" value="<?php echo($this->q35Answer);?>">
    <input type="hidden" id="q41_hidden" name="q4_1" value="<?php echo($this->q41Answer);?>">
    <input type="hidden" id="q42_hidden" name="q4_2" value="<?php echo($this->q42Answer);?>">
    <input type="hidden" id="q43_hidden" name="q4_3" value="<?php echo($this->q43Answer);?>">
    <input type="hidden" id="q44_hidden" name="q4_4" value="<?php echo($this->q44Answer);?>">
    <input type="hidden" id="q45_hidden" name="q4_5" value="<?php echo($this->q45Answer);?>">
    <input type="hidden" name="region" value="<?php echo($this->region);?>">
    <input type="hidden" name="business_model" value="<?php echo($this->business_model);?>">
    <input type="hidden" name="company_size" value="<?php echo($this->company_size);?>">    
    <input type="hidden" name="filter" value="<?php echo($this->currentFilter);?>">
    <center>
    <table>
    	<tr>
    		<td>
			    <div class="infoform_top">
			    	<div class="selectionform">
				    <label>First Name *</label>
					<input type="text" name="first_name" style="width: 200px">
					</div>
				</div>
			</td>
			<td style="padding-left:20px;">	
				<div class="infoform_top">	
			    	<div class="selectionform">
				    <label>Last Name *</label>
					<input type="text" name="last_name" style="width: 200px">
					</div>
				</div>      		
    		</td>
    	</tr>
    	<tr>
    		<td>
			    <div class="infoform">
    				<div class="selectionform">
				    <label>Company Name *</label>
					<input type="text" name="company_name" style="width: 200px">
				    </div>
				</div>
			</td>
			<td style="padding-left:20px;">	
				<div class="infoform">	
					<div class="selectionform">
				    <label>Job Title *</label>
					<input type="text" name="job_title" style="width: 200px">
					</div>

				</div>      		
    		</td>
    	</tr>
    	<tr>
    		<td>
			    <div class="infoform">
    				<div class="selectionform">
				    <label>Email *</label>
					<input type="text" name="email" style="width: 200px">
				    </div>
				</div>
			</td>
			<td style="padding-left:20px;">	
				<div class="infoform">	
					<div class="selectionform">
				    <label>Phone</label>
					<input type="text" name="phone" style="width: 200px">
					</div>

				</div>      		
    		</td>
    	</tr>    	
    	<tr>
    		<td>
			    <div class="infoform_bottom">
					<div class="selectionform">		
				    <label>Country *</label>
				    <select name="state" style="width: 200px">
<option value="0">Please select...</option>
<option value="Afghanistan">Afghanistan</option>
<option value="Aland Islands">Aland Islands</option>
<option value="Albania">Albania</option>
<option value="Algeria">Algeria</option>
<option value="American Samoa">American Samoa</option>
<option value="Andorra">Andorra</option>
<option value="Angola">Angola</option>
<option value="Anguilla">Anguilla</option>
<option value="Antarctica">Antarctica</option>
<option value="Antigua And Barbuda">Antigua And Barbuda</option>
<option value="Argentina">Argentina</option>
<option value="Armenia">Armenia</option>
<option value="Aruba">Aruba</option>
<option value="Australia">Australia</option>
<option value="Austria">Austria</option>
<option value="Azerbaijan">Azerbaijan</option>
<option value="Bahamas">Bahamas</option>
<option value="Bahrain">Bahrain</option>
<option value="Bangladesh">Bangladesh</option>
<option value="Barbados">Barbados</option>
<option value="Belarus">Belarus</option>
<option value="Belgium">Belgium</option>
<option value="Belize">Belize</option>
<option value="Benin">Benin</option>
<option value="Bermuda">Bermuda</option>
<option value="Bhutan">Bhutan</option>
<option value="Bolivia">Bolivia</option>
<option value="Bosnia And Herzegovina">Bosnia And Herzegovina</option>
<option value="Botswana">Botswana</option>
<option value="Bouvet Island">Bouvet Island</option>
<option value="Brazil">Brazil</option>
<option value="British Indian Ocean Territory">British Indian Ocean Territory</option>
<option value="Brunei Darussalam">Brunei Darussalam</option>
<option value="Bulgaria">Bulgaria</option>
<option value="Burkina Faso">Burkina Faso</option>
<option value="Burundi">Burundi</option>
<option value="Cambodia">Cambodia</option>
<option value="Cameroon">Cameroon</option>
<option value="Canada">Canada</option>
<option value="Cape Verde">Cape Verde</option>
<option value="Cayman Islands">Cayman Islands</option>
<option value="Central African Republic">Central African Republic</option>
<option value="Chad">Chad</option>
<option value="Chile">Chile</option>
<option value="China">China</option>
<option value="Christmas Island">Christmas Island</option>
<option value="Cocos (Keeling) Islands">Cocos (Keeling) Islands</option>
<option value="Colombia">Colombia</option>
<option value="Comoros">Comoros</option>
<option value="Congo">Congo</option>
<option value="Congo DRC">Congo DRC</option>
<option value="Cook Islands">Cook Islands</option>
<option value="Costa Rica">Costa Rica</option>
<option value="Côte d'Ivoire">Côte d'Ivoire</option>
<option value="Croatia">Croatia</option>
<option value="Cyprus">Cyprus</option>
<option value="Czech Republic">Czech Republic</option>
<option value="Denmark">Denmark</option>
<option value="Djibouti">Djibouti</option>
<option value="Dominica">Dominica</option>
<option value="Dominican Republic">Dominican Republic</option>
<option value="Ecuador">Ecuador</option>
<option value="Egypt">Egypt</option>
<option value="El Salvador">El Salvador</option>
<option value="Equatorial Guinea">Equatorial Guinea</option>
<option value="Eritrea">Eritrea</option>
<option value="Estonia">Estonia</option>
<option value="Ethiopia">Ethiopia</option>
<option value="Falkland Islands (Malvinas)">Falkland Islands (Malvinas)</option>
<option value="Faroe Islands">Faroe Islands</option>
<option value="Fiji">Fiji</option>
<option value="Finland">Finland</option>
<option value="France">France</option>
<option value="French Guiana">French Guiana</option>
<option value="French Polynesia">French Polynesia</option>
<option value="French Southern Territories">French Southern Territories</option>
<option value="Gabon">Gabon</option>
<option value="Gambia">Gambia</option>
<option value="Georgia">Georgia</option>
<option value="Germany">Germany</option>
<option value="Ghana">Ghana</option>
<option value="Gibraltar">Gibraltar</option>
<option value="Greece">Greece</option>
<option value="Greenland">Greenland</option>
<option value="Grenada">Grenada</option>
<option value="Guadeloupe">Guadeloupe</option>
<option value="Guam">Guam</option>
<option value="Guatemala">Guatemala</option>
<option value="Guinea">Guinea</option>
<option value="Guinea-Bissau">Guinea-Bissau</option>
<option value="Guyana">Guyana</option>
<option value="Haiti">Haiti</option>
<option value="Honduras">Honduras</option>
<option value="Hong Kong">Hong Kong</option>
<option value="Hungary">Hungary</option>
<option value="Iceland">Iceland</option>
<option value="India">India</option>
<option value="Indonesia">Indonesia</option>
<option value="Iraq">Iraq</option>
<option value="Ireland">Ireland</option>
<option value="Israel">Israel</option>
<option value="Italy">Italy</option>
<option value="Jamaica">Jamaica</option>
<option value="Japan">Japan</option>
<option value="Jordan">Jordan</option>
<option value="Kazakhstan">Kazakhstan</option>
<option value="Kenya">Kenya</option>
<option value="Kiribati">Kiribati</option>
<option value="Korea, South">Korea, South</option>
<option value="Kuwait">Kuwait</option>
<option value="Kyrgyzstan">Kyrgyzstan</option>
<option value="Laos">Laos</option>
<option value="Latvia">Latvia</option>
<option value="Lebanon">Lebanon</option>
<option value="Lesotho">Lesotho</option>
<option value="Liberia">Liberia</option>
<option value="Libyan Arab Jamahiriya">Libyan Arab Jamahiriya</option>
<option value="Liechtenstein">Liechtenstein</option>
<option value="Lithuania">Lithuania</option>
<option value="Luxembourg">Luxembourg</option>
<option value="Macao">Macao</option>
<option value="Macedonia">Macedonia</option>
<option value="Madagascar">Madagascar</option>
<option value="Malawi">Malawi</option>
<option value="Malaysia">Malaysia</option>
<option value="Maldives">Maldives</option>
<option value="Mali">Mali</option>
<option value="Malta">Malta</option>
<option value="Marshall Islands">Marshall Islands</option>
<option value="Martinique">Martinique</option>
<option value="Mauritania">Mauritania</option>
<option value="Mauritius">Mauritius</option>
<option value="Mayotte">Mayotte</option>
<option value="Mexico">Mexico</option>
<option value="Micronesia">Micronesia</option>
<option value="Moldova, Republic Of">Moldova, Republic Of</option>
<option value="Monaco">Monaco</option>
<option value="Mongolia">Mongolia</option>
<option value="Montenegro">Montenegro</option>
<option value="Montserrat">Montserrat</option>
<option value="Morocco">Morocco</option>
<option value="Mozambique">Mozambique</option>
<option value="Myanmar">Myanmar</option>
<option value="Namibia">Namibia</option>
<option value="Nauru">Nauru</option>
<option value="Nepal">Nepal</option>
<option value="Netherlands">Netherlands</option>
<option value="Netherlands Antilles">Netherlands Antilles</option>
<option value="New Caledonia">New Caledonia</option>
<option value="New Zealand">New Zealand</option>
<option value="Nicaragua">Nicaragua</option>
<option value="Niger">Niger</option>
<option value="Nigeria">Nigeria</option>
<option value="Niue">Niue</option>
<option value="Norfolk Island">Norfolk Island</option>
<option value="Northern Mariana Islands">Northern Mariana Islands</option>
<option value="Norway">Norway</option>
<option value="Oman">Oman</option>
<option value="Pakistan">Pakistan</option>
<option value="Palau">Palau</option>
<option value="Palestinian Territory">Palestinian Territory</option>
<option value="Panama">Panama</option>
<option value="Papua New Guinea">Papua New Guinea</option>
<option value="Paraguay">Paraguay</option>
<option value="Peru">Peru</option>
<option value="Philippines">Philippines</option>
<option value="Pitcairn">Pitcairn</option>
<option value="Poland">Poland</option>
<option value="Portugal">Portugal</option>
<option value="Puerto Rico">Puerto Rico</option>
<option value="Qatar">Qatar</option>
<option value="Reunion">Reunion</option>
<option value="Romania">Romania</option>
<option value="Russian Federation">Russian Federation</option>
<option value="Rwanda">Rwanda</option>
<option value="Saint Helena">Saint Helena</option>
<option value="Saint Kitts And Nevis">Saint Kitts And Nevis</option>
<option value="Saint Lucia">Saint Lucia</option>
<option value="Saint Pierre And Miquelon">Saint Pierre And Miquelon</option>
<option value="Samoa">Samoa</option>
<option value="San Marino">San Marino</option>
<option value="São Tomé and Príncipe">São Tomé and Príncipe</option>
<option value="Saudi Arabia">Saudi Arabia</option>
<option value="Senegal">Senegal</option>
<option value="Serbia">Serbia</option>
<option value="Seychelles">Seychelles</option>
<option value="Sierra Leone">Sierra Leone</option>
<option value="Singapore">Singapore</option>
<option value="Slovakia">Slovakia</option>
<option value="Slovenia">Slovenia</option>
<option value="Solomon Islands">Solomon Islands</option>
<option value="Somalia">Somalia</option>
<option value="South Africa">South Africa</option>
<option value="Spain">Spain</option>
<option value="Sri Lanka">Sri Lanka</option>
<option value="Suriname">Suriname</option>
<option value="Svalbard And Jan Mayen">Svalbard And Jan Mayen</option>
<option value="Swaziland">Swaziland</option>
<option value="Sweden">Sweden</option>
<option value="Switzerland">Switzerland</option>
<option value="Taiwan">Taiwan</option>
<option value="Tajikistan">Tajikistan</option>
<option value="Tanzania">Tanzania</option>
<option value="Thailand">Thailand</option>
<option value="Timor-Leste">Timor-Leste</option>
<option value="Togo">Togo</option>
<option value="Tokelau">Tokelau</option>
<option value="Tonga">Tonga</option>
<option value="Trinidad And Tobago">Trinidad And Tobago</option>
<option value="Tunisia">Tunisia</option>
<option value="Turkey">Turkey</option>
<option value="Turkmenistan">Turkmenistan</option>
<option value="Turks And Caicos Islands">Turks And Caicos Islands</option>
<option value="Tuvalu">Tuvalu</option>
<option value="Uganda">Uganda</option>
<option value="Ukraine">Ukraine</option>
<option value="United Arab Emirates">United Arab Emirates</option>
<option value="United Kingdom">United Kingdom</option>
<option value="United States" selected>United States</option>
<option value="Uruguay">Uruguay</option>
<option value="Uzbekistan">Uzbekistan</option>
<option value="Vanuatu">Vanuatu</option>
<option value="Vatican City States">Vatican City States</option>
<option value="Venezuela">Venezuela</option>
<option value="Viet Nam">Viet Nam</option>
<option value="Virgin Islands, British">Virgin Islands, British</option>
<option value="Virgin Islands, U.S.">Virgin Islands, U.S.</option>
<option value="Wallis And Futuna">Wallis And Futuna</option>
<option value="Western Sahara">Western Sahara</option>
<option value="Yemen">Yemen</option>
<option value="Zambia">Zambia</option>
<option value="Zimbabwe">Zimbabwe</option>
					</select>
					</div> 
				</div>
			</td>
			<td style="padding-left:20px;">	
				<div class="infoform_bottom">
				&nbsp;	
				</div>      		
    		</td>
    	</tr>   
    	<tr>
    		<td style="padding-left:10px;" colspan="2">
    		<table>
    			<tr>
    			<td valign="top"><input type="checkbox" name="disclosure" value="Yes"></td>
    			<td>
	    			<div id="disclosure-block">
		    		I acknowledge that I have read the SAP <a style="color:#00b3ee;" href="http://go.sap.com/about/legal/privacy.html" target="privacy">Privacy Statement (+)</a> (which is based on the country/region selection above) 
		    		and consent to the processing of my personal data in accordance with the terms of the Privacy Statement</a>. 
		    		Based on my country/region selection above, my data will be controlled by SAP USA.<br> 
		    		<a style="color:#00b3ee;" href="http://go.sap.com/about/legal/impressum.html" target="legal">Legal Disclosure (+)</a><br>
		    		By submitting this registration, you acknowledge that you have read our <a style="color:#00b3ee;" href="http://go.sap.com/about/legal/privacy.html" target="privacy">Privacy Statement</a>. 
		    		Please note that the referenced SAP Global Permission Marketing Policy is applicable also to hybris and its affiliates as 
		    		they are ultimately owned by SAP USA. References to SAP in the Privacy Statement and in the 
		    		SAP Global Permission Marketing Policy shall be deemed to include references to hybris.<br>
		    		<br>
		    		Based on your country selection, your data will be controlled by the <a style="color:#00b3ee;" href="https://www.hybris.com/en/locations" target="location">hybris or SAP legal entity in that country</a> or, 
		    		where no such country entity exists, by hybris AG.
					</div>
				</td>
    			</tr>
    		</table>	
    		</td>
    	</tr> 
    	<tr>
    		<td colspan="2" style="padding-left:10px;">
    		<div id="disclosure-block2">
			If you have any questions, please contact us at <a style="color:#00b3ee;" href="mailto:sales@hybris.com">sales@hybris.com</a>.
			</div>
    		</td>
    	</tr>	    	
    </table>
    </center>


	<div class="submitcontent"><input type="submit" class="imagebtn-sm" value="SUBMIT"></div>
	
	</form>
  </div>
<!-- Popup form ends-->
  
	<div id="incomplete_error" class="error-msg">
	<span>One or more required fields are missing values</span>
	</div>
	
	<div id="disclosure_error" class="error-msg">
	<span>Agreement is not accepted.</span>
	</div>
	  
</body>
</html>