<!DOCTYPE html>
<html>
	<body>
		<form action="/admin/resetuserpassword" method="POST">
			<div align="center" style="width:100%;">
				<br>Please enter your new password:&nbsp;<input type="password" name="newPassword" size="40" required placeholder="Please enter your new password">&nbsp;<input type="submit" value="Submit">
				<input type="hidden" name="id" value="<?php echo($_GET['id']);?>">
				<input type="hidden" name="password" value="<?php echo($_GET['password']);?>">
			</div>
		</form>
	</body>
</html>